apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: replications.registries.mittwald.de
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: phase
    name: Status
    type: string
  - JSONPath: .status.id
    description: harbor replication id
    name: ID
    type: integer
  - JSONPath: .spec.enabled
    description: harbor replication id
    name: Enabled
    type: boolean
  - JSONPath: .status.source
    description: source registry
    name: Source
    type: string
  - JSONPath: .status.destination
    description: destination registry
    name: Destination
    type: string
  group: registries.mittwald.de
  names:
    kind: Replication
    listKind: ReplicationList
    plural: replications
    singular: replication
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Replication is the Schema for the replications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ReplicationSpec defines the desired state of Replication
          properties:
            creator:
              type: string
            description:
              type: string
            destNamespace:
              description: The destination namespace If left empty, the resource will
                be but in the same namespace as the source
              type: string
            destRegistry:
              description: Destination Registry Reference to a registry cr
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            enabled:
              description: Whether the policy is enabled or not
              type: boolean
            filters:
              description: The replication policy filter array
              items:
                description: ReplicationFilter holds the specifications of a replication
                  filter
                properties:
                  type:
                    description: The replication policy filter type.
                    type: string
                  value:
                    description: The value of replication policy filter.
                    type: string
                type: object
              type: array
            name:
              description: The name of the replication
              type: string
            override:
              description: Whether to override the resources on the destination registry
                or not
              type: boolean
            parentInstance:
              description: ParentInstance is a LocalObjectReference to the name of
                the harbor instance the replication policy gets created for
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            replicateDeletion:
              description: Whether to replicate the deletion operation
              type: boolean
            srcRegistry:
              description: Source Registry Reference to a registry cr
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            trigger:
              description: The replication policy trigger type
              properties:
                triggerSettings:
                  description: TriggerSettings holds the settings of a trigger
                  properties:
                    cron:
                      type: string
                  required:
                  - cron
                  type: object
                type:
                  type: string
              type: object
            triggerAfterCreation:
              type: boolean
          required:
          - name
          - override
          - parentInstance
          type: object
        status:
          description: ReplicationStatus defines the observed state of Replication
          properties:
            destination:
              type: string
            id:
              description: The replication ID is written back from the held replication
                ID.
              format: int64
              type: integer
            lastTransition:
              description: Time of last observed transition into this state
              format: date-time
              type: string
            message:
              type: string
            name:
              type: string
            phase:
              type: string
            source:
              description: The respective source and destination registries
              type: string
          required:
          - message
          - name
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
